[build]
  publish = "."
  command = "python setup_project.py && python create-essay-html.py && python generate_pdf_epub.py && python generate_sitemap.py"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[site]
  name = "paulgramessays"

# Redirect all routes to the index.html file (SPA style)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for essay pages
[[redirects]]
  from = "/essays/*"
  to = "/essays/:splat"
  status = 200

# Redirect for download pages
[[redirects]]
  from = "/downloads/*"
  to = "/downloads/:splat"
  status = 200

[dev]
  command = "python -m http.server"
  port = 8888
  publish = "."
